project_id = "kqzsgqqwnthclrlcfkgs"

[functions.retell-webhook]
verify_jwt = false

[functions.twilio-webhook]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
